<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes)</DefaultItemExcludes>

    <Version>1.1.0</Version>
    <Authors>Peter Laudy</Authors>
    <Company>Zestien3</Company>

    <!-- Set this to true if you enable server-side prerendering -->
    <BuildServerSideRenderer>false</BuildServerSideRenderer>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.*" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.*" />
    <PackageReference Include="Google.Apis.PeopleService.v1" Version="1.*" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="MSBuild.StructuredLogger" Version="2.2.386" Condition="'$(Configuration)' == 'Debug'" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove=".\appsettings.*.json" />
  </ItemGroup>
</Project>
